apiVersion: v1
kind: Secret
metadata:
  name: {{ include "checkstack.fullname" . }}-config
  labels:
    {{- include "checkstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
